### ISSUE TITLE
test failures: cancel_nop, cancel_pipe

### ISSUE THREAD

**Issue by jonathanstrong** [quininer/io-uring#23]
hello,

Ran the tests on my machine and encountered some failures. Be forewarned that I updated my kernel to run this in the first place, so possibly it's some kind of compatibility or versioning issue of the underlying system I'm on.

Am running ubuntu 18.04 on a workstation with older xeons, and the kernel had been at 4.15 (I think). Now running 5.1.21:

```console
$ uname -a
Linux coolidge 5.1.21-050121-generic #201907280731 SMP Sun Jul 28 07:34:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

When I run the tests, the ones in tests/cancel.rs hang. I've let them run more than 5 minutes without completion. When I run strace on the test runner process, that somehow triggers the test actually failing.

During the hang, there are actually two processes running. `strace` on one of them results in this:

```console
$ sudo strace -p 18074
strace: Process 18074 attached
restart_syscall(<... resuming interrupted futex ...>^Cstrace: Process 18074 detached
 <detached ...>
```

Then, `strace` on the other pushes the test runner past its deadlock:

```console
strace: Process 18076 attached
syscall_0x1aa(0x4, 0x1, 0x2, 0x1, 0, 0x80) = 0x1
close(7)                                = 0
close(5)                                = 0
munmap(0x7fd7b8071000, 160)             = 0
munmap(0x7fd7b8072000, 256)             = 0
munmap(0x7fd7b8070000, 272)             = 0
close(4)                                = 0
futex(0x557afd529a9c, FUTEX_WAKE_PRIVATE, 1) = 1
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
munmap(0x7fd7b8076000, 8192)            = ? <unavailable>
+++ exited with 101 +++
```

The test failure output is:

```console
running 2 tests
test test_cancel_nop ... FAILED
test test_cancel_pipe ... test test_cancel_pipe has been running for over 60 seconds
test test_cancel_pipe ... FAILED

failures:

---- test_cancel_nop stdout ----
thread 'test_cancel_nop' panicked at 'assertion failed: `(left == right)`
  left: `-9`,
 right: `-2`', tests/cancel.rs:42:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_cancel_pipe stdout ----
thread 'test_cancel_pipe' panicked at 'assertion failed: `(left == right)`
  left: `-4`,
 right: `-125`', tests/cancel.rs:96:5
```

The values (-9/-2, -4/-125) are the same on successive runs. Switching which features are enabled does not seem to change this behavior. 

Hopefully this is useful to you. This is my first experience with either the rust io-uring library or the io_uring syscalls, so apologies if I am doing anything wrong. Thanks!

**Comment by quininer** [comment]
The kernel behavior is different between different versions, I don't plan to support linux versions below 5.4 (it's lts) because it's tricky.

**Comment by quininer** [comment]
And, `AsyncCancel` is an opcode added in 5.5, test failure is expected behavior.
