### ISSUE TITLE
Incorrect error handling while updating file registrations.

### ISSUE THREAD

**Issue by VecrsIssues** [quininer/io-uring#25]
Reproduction:

Step one: place a file named `update_file_registrations.rs` into the example directory containing this text: 

    use io_uring::{reg, unreg, IoUring};
    use std::{io::Result, iter, os::unix::io::IntoRawFd};
    use tempfile::tempfile;
    
    fn open() -> Vec<i32> {
        iter::repeat_with(|| tempfile().unwrap().into_raw_fd()).take(10).collect()
    }
    
    fn main() -> Result<()> {
        let uring = IoUring::new(256)?;
    
        let fds = open();
        let new_fds = open();
    
        uring.register(reg::Target::Files(&fds))?;
        uring.register(reg::Target::FilesUpdate { offset: 0, fds: &new_fds })?;
    
        uring.unregister(unreg::Target::Files)?;
    
        Ok(())
    }

Step two: execute `$ cargo run --example update_file_registrations`.

Expected result: example completes with no output.

Actual result: example returns `Error: Os { code: 0, kind: Other, message: "Success" }`.

My code is based on this test that successfully passes on my system:
https://git.kernel.dk/cgit/liburing/tree/test/file-update.c#n62

**Comment by VecrsIssues** [comment]
This line might be the cause, but I'm not familiar enough with the interface to know what's correct here.

https://github.com/quininer/io-uring/blob/ec2dae7ed50316bcc219e16b51c09dede1afc680/src/register.rs#L10

I think the update command returns the number of updated entries on success, so a simple equality check with zero would be wrong.

**Comment by quininer** [comment]
Thank you!

The behavior of `io_uring_register` has changed, and I implemented this code with reference to [manpage](https://github.com/axboe/liburing/blob/master/man/io_uring_register.2#L229).  :(

I will fix it later in `0.3.4`, but change `register` return value is a break change, so I leave it to `0.4`.

**Comment by VecrsIssues** [comment]
Great, this appears to fix my issue.

As I said, I'm not very familiar with this interface, but are you sure that `last_os_error()`/ERRNO is the correct place to retrieve the error code from in this case?

You can close this issue if you think the problem is satisfactorily solved.

**Comment by quininer** [comment]
Yes, I believe that using `last_os_error()` is correct.
